import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
#
# SSL is terminated by Traefik (the reverse proxy), so we do not use
# force_ssl here. Enabling force_ssl causes Plug.SSL to redirect
# WebSocket upgrade requests (GET /live/websocket) with a 301,
# which breaks Phoenix LiveView WebSocket connections.
config :squaredle_solver, SquaredleSolverWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
